---
title: "Dice"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dice}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(TailRiskAnalyzer)
library(ggplot2)
library(dplyr)
```


# Sample of possible outcomes

```{r}
# create empty dataframe with 2 columns, index, and value
df <- data.frame(
  index = integer(),
  round = integer(),
  value = double()
)

num_lines <- 1000
for (i in 1:num_lines) {
  cur_run <- die_game_seq(4, 6, payoffs = c(0.5, 1.5, 1.05, 1.05, 1.05, 1.05))
  for (round in seq_along(cur_run$results)) {
    value <- cur_run$results[round]
    df <- df |> add_row(index = i, round = round, value = value)
  }
}

create_side_by_side_plot(df)
```

# Theoretical Dice Game with all possibilities present in proper proportion

```{r}
toss_result_list <- generate_die_sequences(5, 6)
# toss_result_list

df <- data.frame(
  index = integer(),
  round = integer(),
  value = double()
)

# iterate over rows of toss_result_list
for (i in seq(from = 1, to = nrow(toss_result_list))) {
  # print(i)
  cur_run <- calc_score_for_die(toss_result_list[i, ],
    payoffs = c(0.5, 1.5, 1.05, 1.05, 1.05, 1.05),
    min_bet = 50, betting_fraction = 0.75
  )
  for (round in seq_along(cur_run)) {
    value <- cur_run[round]
    df <- df |> add_row(index = i, round = round, value = value)
  }
}

create_side_by_side_plot(df)
```
