---
title: "test-animation"
author: "Thomas Misikoff"
date: "2024-02-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
devtools::install_github("misikoff/TailRiskAnalyzer")
library(gganimate)
library(ggplot2)
library(gifski)
library(TailRiskAnalyzer)
library(dplyr)
library(tidyverse)
library(moments)
```


```{r}
# use tidyverse to load ./SPY.csv
SPY <- read.csv("./SPY.csv")
SPY$Proportion.Change <- (SPY$Close - lag(SPY$Close)) / lag(SPY$Close)
hist(SPY$Proportion.Change * 100, breaks = 100, main = "SPY Daily % Change", xlab = "Daily Returns %", col = "lightblue")
```

```{r}
mean_spy_change <- mean(SPY$Proportion.Change, na.rm = TRUE)
var_spy_change <- var(SPY$Proportion.Change, na.rm = TRUE)

# plot normal distribution
ggplot(data.frame(x = c(-0.05, 0.05)), aes(x)) +
  stat_function(fun = dnorm, args = list(mean = mean_spy_change, sd = sqrt(var_spy_change))) +
  labs(title = "SPY Daily Returns", x = "Daily Returns", y = "Density") +
  theme_minimal() +
  # add histogram of spy returns
  geom_histogram(data = SPY, aes(Proportion.Change, y = after_stat(density)), bins = 100, alpha = 0.5)
# + scale_x_log10()
```


```{r}
kurtosis(SPY$Proportion.Change, na.rm = TRUE)
```



