---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(TailRiskAnalyzer)
```

Here is the function. It is important because ...

```{r}
coin_toss_seq <- function(
    num_rounds = 1,
    heads_prob = 0.5,
    initial = 100,
    head_factor = 2,
    tails_factor = 0.5,
    min_bet = 1,
    max_payout = NA,
    betting_fraction = 1) {
  results <- c(initial)
  toss_results <- rbinom(num_rounds, size = 1, prob = heads_prob)


  # betting_fraction must be between 0 and 1 for now, could add leverage later
  for (res in toss_results) {
    current_funds <- results[length(results)]
    new_bet <- current_funds * betting_fraction
    reserve <- current_funds - new_bet

    if (!is.na(max_payout) && current_funds >= max_payout) {
      break
    }

    if (new_bet < min_bet) {
      break
    }

    if (res == 0) {
      # tails
      results <- c(results, reserve + (new_bet * tails_factor))
    } else {
      # heads
      results <- c(results, reserve + (new_bet * head_factor))
    }
  }

  if (!is.na(max_payout)) {
    results[length(results)] <- min(results[length(results)], max_payout)
  }

  return(
    list(
      results = results,
      toss_results = toss_results,
      payout = results[length(results)]
    )
  )
}

hmm <- coin_toss_seq(50)
print(hmm$results)
print(hmm$toss_results)
print(hmm$payout)
```

```{r}
lots_of_results <- c()
for (i in 0:50) {
  res <- coin_toss_seq(50, betting_fraction = 0.75, max_payout = 300)
  print(res$payout)
  lots_of_results <- c(lots_of_results, res$payout)
}
# lots_of_results
hist(lots_of_results, breaks=seq(0, 300, 10))
# hist(c(1, 1, 2, 1))

# get_kelly_bet(0.5, 2, 0.5)

median(c(1,1,5,20))


```

```{r}
# for 

df <- data.frame(
    betting_fraction = c(0),
    median_payout = c(0)
  )

num_samples = 10000
for(frac in seq(0,1,0.05)) {
  lots_of_results <- c()
  for (j in 1:num_samples) {
    res <- coin_toss_seq(100, betting_fraction = frac, heads_prob = 0.5, max_payout = 100000000)
    # print(res$payout)
    lots_of_results <- c(lots_of_results, res$payout)
  }
  df = df |> add_row(betting_fraction = frac, median_payout = median(lots_of_results))
}
df |> ggplot(aes(x = betting_fraction, y = median_payout)) + geom_point()

# get_kelly_bet(0.5, 2, 0.5)

# get_kelly_bet(0.5, 1, 0)

```
