#' Get the probability that an event was generated by a normal distribution
#'  given the alternative is a t-distribution with given degrees of freedom.
#'
#' @param prior The prior probability that the event was
#' generated by a normal distribution
#' @param z The Z-score of the event,
#' i.e., the number of standard deviations away from the mean
#' @param t_df The degrees of freedom for the t-distribution
#'
#' @return A probability
#' @export
#'
#' @examples
#' is_normal_given_event(0.999, 10, 2)
p_normal_given_event <- function(prior = 0.5, z = 10, t_df = 2) {
  p_event_given_norm <- stats::pnorm(z, lower.tail = FALSE)
  p_event_given_t <- stats::pt(z, t_df, lower.tail = FALSE)

  numerator <- prior * p_event_given_norm
  denominator <- (1 - prior) * p_event_given_t + prior * p_event_given_norm

  # print(numerator)
  # print(denominator)
  # print(prior)
  # print(p_event_given_t)
  # print(p_event_given_norm)
  # print((1 - prior) * p_event_given_t)
  # print(prior * p_event_given_norm)

  # if denominator is negative,
  # a floating point error has occurred, probably in 1 - prior
  # e.g., 1 - 0.99999999999999999 = -2.220446e-16
  if (denominator < 0) {
    stop("A floating point error has occured.
    This is usually based on a prior being extremely close to 1.")
  }

  return(numerator / denominator)
}
